// Bug 3: does a re-anchored link follow when the ORIGIN node is moved?
import { chromium } from 'playwright'
const b = await chromium.launch({ headless: true })
const page = await b.newPage({ viewport: { width: 1600, height: 900 } })
await page.goto(process.env.COMFY_URL ?? 'http://127.0.0.1:8187', { waitUntil: 'domcontentloaded', timeout: 90_000 })
await page.waitForFunction(() => window.app && window.app.graph, null, { timeout: 120_000 })
await page.waitForTimeout(3000)
const ids = await page.evaluate(async () => {
  const g=window.app.graph,L=window.LiteGraph
  g.clear()
  const ck=L.createNode('CheckpointLoaderSimple'); ck.pos=[80,420]; g.add(ck)
  const B=L.createNode('CLIPTextEncode'); B.pos=[520,120]; g.add(B)
  const C=L.createNode('CLIPTextEncode'); C.pos=[1000,120]; g.add(C)
  ck.connect(1,B,0); g.setDirtyCanvas(true,true); await new Promise(r=>setTimeout(r,1700))
  return { ck:String(ck.id), B:String(B.id), C:String(C.id) }
})
const from = await page.evaluate(i=>{const p=document.querySelector(`.cablemanagement-pin[data-cablemanagement-node="${i.B}"][data-cablemanagement-index="0"]`);const r=p.getBoundingClientRect();return[r.x+r.width/2,r.y+r.height/2]},ids)
const to = await page.evaluate(i=>{const d=document.querySelector(`[data-slot-key="${i.C}-in-0"]`);const r=d.getBoundingClientRect();return[r.x+r.width/2,r.y+r.height/2]},ids)
await page.mouse.move(...from); await page.mouse.down(); await page.mouse.move(to[0],to[1],{steps:10}); await page.mouse.up()
await page.waitForTimeout(1000)
const mid = i => page.evaluate(j => { const g=window.app.graph,C=g.getNodeById(Number(j.C)); const l=g.getLink(C.inputs[0].link); return l?._pos?[Math.round(l._pos[0]),Math.round(l._pos[1])]:null }, i)
const before = await mid(ids)
// move the ORIGIN node (B, which carries the pin the link is anchored to)
await page.evaluate(i => { const n=window.app.graph.getNodeById(Number(i.B)); n.pos=[n.pos[0], n.pos[1]+260]; window.app.graph.setDirtyCanvas(true,true) }, ids)
await page.waitForTimeout(900)
const after = await mid(ids)
console.log('link midpoint before origin moved:', JSON.stringify(before))
console.log('link midpoint after  origin moved:', JSON.stringify(after))
console.log('followed:', before && after && Math.abs(after[1]-before[1]) > 50 ? 'YES' : 'NO (frozen)')
await b.close()
